version: '2'

services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: rbackup
      MYSQL_DATABASE: rbackup
  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3369:3369"
